### Register
POST http://localhost:3001/register HTTP/1.1
content-type: application/json

{
   "username": "taimoorkhan",
   "firstname": "Taimoor",
   "lastname": "khan",
   "email": "Taimoor10@gmail.com",
   "password": "12345678"
}

### Login
POST http://localhost:3001/login HTTP/1.1
content-type: application/json

{
   "email": "Taimoor9@gmail.com",
   "password": "12345678"
}

###
GET http://localhost:3001/user/43adc184-6334-4d0e-8b82-5bc4e47b4860 HTTP/1.1 